import { ProductType } from "@/@types/api/product";
import ProductAccountOrder from "@/components/products/product-account-order";

export interface ProductOrderType  extends ProductType {
  order: boolean
}


const productsData: ProductOrderType[] = [
  {
    id: 1,
    image: "/icons/products/1.png",
    name: "Laptop v23",
    description: "Laptop v23",
    default_price: 300,
    quantity: 1,
    status: "active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
    price: 300,
    oldPrice: 559,
    rating: 4,
    category: "Electronics",
    sale: true,
  order: false},
  {
    id: 2,
    image: "/icons/products/2.png",
    name: "Laptop v23",
    description: "Laptop v23",
    default_price: 300,
    quantity: 1,
    status: "active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
    price: 300,
    oldPrice: 559,
    rating: 4,
    category: "Electronics",
    sale: true,
  order: false},
  {
    id: 3,
    image: "/icons/products/3.png",
    name: "Laptop v23",
    description: "Laptop v23",
    default_price: 300,
    quantity: 1,
    status: "active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
    price: 300,
    oldPrice: 559,
    rating: 4,
    category: "Electronics",
    sale: true,
  order: false},
  {
    id: 4,
    image: "/icons/products/4.png",
    name: "Laptop v23",
    description: "Laptop v23",
    default_price: 300,
    quantity: 1,
    status: "active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
    price: 300,
    oldPrice: 559,
    rating: 4,
    category: "Electronics",
    sale: true,
  order: false},
  {
    id: 5,
    image: "/icons/products/5.png",
    name: "Laptop v23",
    description: "Laptop v23",
    default_price: 300,
    quantity: 1,
    status: "active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
    price: 300,
    oldPrice: 559,
    rating: 4,
    category: "Electronics",
    sale: true,
  order: false},
  {
    id: 6,
    image: "/icons/products/6.png",
    name: "Laptop v23",
    description: "Laptop v23",
    default_price: 300,
    quantity: 1,
    status: "active",
    created_at: "2023-01-01",
    updated_at: "2023-01-01",
    price: 300,
    oldPrice: 559,
    rating: 4,
    category: "Electronics",
    sale: true,
  order: false},
];

export default function AccountOverview() {
  return <div>نظرة عامة على الحساب</div>;
}
